### ISSUE TITLE
Prepare Codebook in RedHen Website for reference of Audio Tags 

### ISSUE THREAD

**Issue by technosaby** [technosaby/gsoc2022#29]

**Comment by technosaby** [comment]
@brucearctor @turnermarkb Can you please take a look at the PR if the cookbook format is okay?

**Comment by brucearctor** [comment]
Living on a boat the next few days...  not likely to have a look for a bit

**Comment by brucearctor** [comment]
So there are potentially two types of coding/codebook:

(a) trying to make the file sizes smaller ...  ex: use just a small integer rather than a longer string of many characters.  

(b) an extension of that, where even something like:

500,"Inside
501,"Inside
502,"Inside

What are the difference between each of these "inside"?  A longer description might be helpful, and if there isn't some form of known difference, why would they be treated differently ?  


Also, related to format that you share ....  LOTS have an initial " double quotation mark, but not a second one.  Imagining, for a CSV, you might want the entire field to include double quotes ( beginning and end of string/word/words ) or else, I don't understand why you would use the leading double quote.

**Comment by technosaby** [comment]
@brucearctor Sorry this was a mistake from my end. Can you please check if [this](https://github.com/technosaby/gsoc2022/tree/main/tagging_audio_effects/codebook) is okay now ?

**Comment by technosaby** [comment]
@brucearctor The latest version looks good, right ?

**Comment by brucearctor** [comment]
I didn't look at all the lines ... the description/text/word(s):  are they all sufficiently descriptive to identify [ potentially yes, but I don't know without looking at all closely ].

**Comment by technosaby** [comment]
@brucearctor I have modified this based as you suggested in the meeting last day. Please refer to this [PR](https://github.com/technosaby/gsoc2022/pull/32/).
