### ISSUE TITLE
Create a set of sample test cases based on Red Hen's data for  baselining

### ISSUE THREAD

**Issue by technosaby** [technosaby/gsoc2022#3]
1. Take a set of 10 videos
2. Extract the audio and then use Yamnet to get the taggings
3. Process the tagging and create output based on Redhen's format

**Comment by technosaby** [comment]
@brucearctor @turnermarkb As discussed, I selected some Redhen videos to run through the model. I see the following data.
The first video did not give much variations, while the second video have a good amount of tagging for different classes.

![2010-01-01_2335_US_CSPAN2_World_War_II](https://user-images.githubusercontent.com/89327872/176492354-4a70ccfb-9648-4aa1-9925-1a39eb6b2148.jpg)
![2021-01-01_0300_US_WUAB_19_News_at_10PM](https://user-images.githubusercontent.com/89327872/176492420-80b16a69-66c3-438e-b7d5-74c31b1d13e5.jpg)
![2021-01-01_2200_US_FOX-News_The_Five](https://user-images.githubusercontent.com/89327872/176492437-3cd6442d-84ff-495c-a88a-b438e1c175ef.jpg)

I am also generating the output in this form as of now (not Redhen format). I am working on that to generate in RedHens format. 
<img width="676" alt="Screenshot 2022-06-29 at 10 26 01 PM" src="https://user-images.githubusercontent.com/89327872/176493351-170f02c4-a8b8-4a20-a80e-e2a73cdf40c2.png">

What next steps should I prioritise?

**Comment by brucearctor** [comment]
I generally like to ensure I can get the minimum requirements met ... So, while potentially easy, you might want to start to arrive at the file output format -- coming up with a proposed filetype/format will be good to allow time for others to review/comment, and any revisions.  Seems worth doing with plenty of time, since is something that must eventually get done.
